groups:
  - name: alertmanager-ops
    rules:
      # Alertmanagerがダウン
      - alert: AlertmanagerDown
        expr: absent(up{job="alertmanager"} == 1)
        for: 2m
        labels: {severity: critical, service: inkaritsu}
        annotations:
          summary: "Alertmanager down"

      # 通知失敗カウンタ（5分平均で増えている）
      - alert: AlertmanagerNotifyFailures
        expr: rate(alertmanager_notifications_failed_total[5m]) > 0
        for: 5m
        labels: {severity: warning, service: inkaritsu}
        annotations:
          summary: "Alertmanager notification failures in last 5m"

      - alert: InkaritsuVersionStale
      # 20分間のサンプル数を job 単位で合算。1件以上あれば問題なし
        expr: sum by (job) (count_over_time(inkaritsu_version_info{job="inkaritsu_webhook_version"}[20m])) < 1
        for: 25m
        labels: {severity: warning, service: inkaritsu}
        annotations:
          summary: "inkaritsu_version_info not refreshed for >20m"
