global:
  resolve_timeout: 2m

route:
  receiver: slack-default
  group_by: ['alertname','service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers: ['severity="critical"']
      receiver: slack-error

receivers:
  - name: slack-default
    slack_configs:
      - api_url_file: /etc/alertmanager/.slack_webhook
        channel: '#alerts'
        send_resolved: true
        title: '{{ .CommonLabels.severity | upper }}: {{ .CommonLabels.alertname }} ({{ .CommonLabels.service | default "inkaritsu" }})'
        text: |-
          {{- range .Alerts }}
          *{{ .Labels.alertname }}* ({{ .Labels.severity }})
          {{ .Annotations.summary | default "no summary" }}
          {{- end }}

  - name: slack-error
    slack_configs:
      - api_url_file: /etc/alertmanager/.slack_webhook_error
        channel: '#alerts-critical'
        send_resolved: true
        title: '{{ .CommonLabels.severity | upper }}: {{ .CommonLabels.alertname }} ({{ .CommonLabels.service | default "inkaritsu" }})'
        text: |-
          {{- range .Alerts }}
          *{{ .Labels.alertname }}* ({{ .Labels.severity }})
          {{ .Annotations.summary | default "no summary" }}
          {{- end }}
