name: ci(ops): auto label SAFE
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  label-safe:
    if: ${{ github.repository_owner == "conquestichi" }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pr = context.payload.pull_request.number;
            // 変更ファイルが .github/workflows/ のみ なら SAFE を付与
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              { owner, repo, pull_number: pr, per_page: 100 }
            );
            const onlyWorkflows = files.every(f => f.filename.startsWith(".github/workflows/"));
            if (onlyWorkflows) {
              await github.rest.issues.addLabels({
                owner, repo, issue_number: pr, labels: ["安全"]
              });
              core.info("Labeled SAFE");
            } else {
              core.info("Skip: not workflows-only change");
            }
