name: ci(ops): auto label SAFE for guardrail PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label-safe:
    if: >
      github.repository == "conquestichi/inga-context-public" &&
      startsWith(github.head_ref, ops/fix-kpi-warn-)
    runs-on: ubuntu-latest
    steps:
      - name: Check changed files & label SAFE
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const pr    = context.payload.pull_request.number;

            // 変更ファイル取得
            const { data: files } = await github.rest.pulls.listFiles({
              owner, repo, pull_number: pr, per_page: 100
            });

            // KPI_CATALOG.yaml のみなら SAFE 付与
            const onlyCatalog =
              files.length === 1 && files[0].filename === "context/KPI_CATALOG.yaml";

            if (!onlyCatalog) {
              core.info("Skip: not catalog-only change");
              return;
            }

            await github.rest.issues.addLabels({
              owner, repo, issue_number: pr, labels: ["安全"]
            });
            core.info(`Labeled PR #${pr} with 安全`);
